package DangNhap_A.Quan;

import static DangNhap_A.Quan.DangNhap.url;
import Model.nhanVien;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.pro1041.util.DialogHelper;
import View.Main;
import com.pro1041.util.ShareHelper;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author HOANG
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }
    String Driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    static String url = "jdbc:sqlserver://localhost:1433;databaseName=quanLyCuaHangThoiTrang;user=sa;password=123;encrypt=false";
    String user = "sa";
    String password = "hung";
    Statement st;
    ResultSet rs;

    public Model.nhanVien findByID(String id) {
        try {
            Class.forName(Driver);
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "select * from nhanVien where maNhanVien=?";
            PreparedStatement pr = con.prepareCall(sql);
            pr.setString(1, id);
            rs = pr.executeQuery();
            if (rs.next()) {
                nhanVien nvM = new nhanVien();
                nvM.setMaNhanVien(rs.getString("maNhanVien"));
                nvM.setHoVaTen(rs.getString("hovaTen"));
                nvM.setMatKhau(rs.getString("matKhau"));
                nvM.setChucVu(rs.getBoolean("chucVu"));
                nvM.setNgaySinh(rs.getDate("ngaySinh"));
                nvM.setGioiTinh(rs.getBoolean("gioiTinh"));
                nvM.setCanCuocCongDan(rs.getString("canCuocCongDan"));
                nvM.setSoDienThoai(rs.getString("soDienThoai"));
                nvM.setHinhAnh(rs.getString("hinhAnh"));
                nvM.setEmail(rs.getString("email"));
                return nvM;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PromptSupport.setPrompt("Username", txtUsername);
        txtUsername.setFont(new java.awt.Font("Lexend Deca", 0, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.setBorder(null);
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 290, 60));

        jButton1.setFont(new java.awt.Font("Lexend Deca", 0, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 250, 50));

        jLabel2.setFont(new java.awt.Font("Lexend Deca", 1, 33)); // NOI18N
        jLabel2.setText("CHÀO MỪNG BẠN TRỞ LẠI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lexend Deca", 0, 18)); // NOI18N
        jLabel3.setText("Chưa có tài khoản? Đăng ký tại ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("đây");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 580, -1, -1));

        PromptSupport.setPrompt("Password", txtPassword);
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setPreferredSize(new java.awt.Dimension(113, 32));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 382, 290, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Colorful Modern Creative Presentation (1000 x 600 px).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        SignUp sg = new SignUp();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String maNhanVien = txtUsername.getText();
            String matKhau = new String(txtPassword.getPassword());
            nhanVien nv = findByID(txtUsername.getText());
            if (nv != null) {
                ShareHelper.USER = nv;
                if (txtPassword.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Chưa Nhập Mật Khẩu", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                } else if (nv.getMaNhanVien().equals(maNhanVien) && nv.getMatKhau().equals(matKhau)) {
                    if (nv.getChucVu()) {
                        JOptionPane.showMessageDialog(this, "Xin chào admin Hùng ĐZ");
                        System.out.println(nv.getMaNhanVien());
                        Main main = new Main();
                        main.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Xin chào Quản Lí SV QUÂN");
                        System.out.println(nv.getMaNhanVien());
                        Main main = new Main();
                        main.setVisible(true);
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu không chính xác!");
                }
            } else {
                DialogHelper.alert("Tên đăng nhập không tồn tại!");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
