/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package nhanVien.View;

import com.pro1041.dao.DAO_nhanVien;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Panel;
import javax.swing.JPanel;
import Model.nhanVien;
import nhanVien.data.nhanVien_data_DAO;
import com.pro1041.datechooser.Button;
import java.awt.event.ActionListener;
import java.util.EventListener;
import javax.swing.JButton;

/**
 *
 * @author hnhut
 */
public class nhanVien_InternalForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form nhanVien_InternalForm
     */
    public nhanVien_InternalForm() {
        initComponents();
        System.out.println("Select All");
        showList_nv();
        setSize(1000, 700);
        nhanVien_showList_container.setLayout(new GridLayout(0, 3));
    }

    public void update() {
        showList_nv();
        getParent().repaint();
    }

    public void clickAdd() {
        System.out.println("showList");
        showList_nv();
    }

    public void CreateSize(int width, int heigt) {
        setSize(width, HEIGHT);
    }

    public void showList_nv() {
        nhanVien_showList_container.removeAll();
        for (nhanVien nv : new nhanVien_data_DAO().selectAll()) {
            NhanVienCard nv_Card = new NhanVienCard(nv, this);
            nhanVien_showList_container.add(nv_Card);
        }
        nhanVien_showList_container.repaint();
    }

    public void showList_nv_byID_almost(String id) {
        nhanVien_showList_container.removeAll();
        System.out.println("M: "+new nhanVien_data_DAO().selectNhanVien_byID_almost(id));
        for (nhanVien nv : new nhanVien_data_DAO().selectNhanVien_byID_almost(id)) {
            NhanVienCard nv_Card = new NhanVienCard(nv, this);
            nhanVien_showList_container.add(nv_Card);
        }
        nhanVien_showList_container.revalidate();
        nhanVien_showList_container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        nhanVien_showList_tbP = new javax.swing.JPanel();
        showList_nav = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        nhanVien_txt_searchID = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVien_showList_container = new javax.swing.JPanel();
        nhanVien_showData_tbP = new javax.swing.JPanel();

        showList_nav.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel16.setText("Search");

        nhanVien_txt_searchID.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nhanVien_txt_searchIDCaretUpdate(evt);
            }
        });
        nhanVien_txt_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVien_txt_searchIDActionPerformed(evt);
            }
        });
        nhanVien_txt_searchID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nhanVien_txt_searchIDPropertyChange(evt);
            }
        });

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showList_navLayout = new javax.swing.GroupLayout(showList_nav);
        showList_nav.setLayout(showList_navLayout);
        showList_navLayout.setHorizontalGroup(
            showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showList_navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(nhanVien_txt_searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showList_navLayout.setVerticalGroup(
            showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showList_navLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhanVien_txt_searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nhanVien_showList_container.setLayout(new java.awt.GridLayout(0, 4));
        jScrollPane1.setViewportView(nhanVien_showList_container);

        javax.swing.GroupLayout nhanVien_showList_tbPLayout = new javax.swing.GroupLayout(nhanVien_showList_tbP);
        nhanVien_showList_tbP.setLayout(nhanVien_showList_tbPLayout);
        nhanVien_showList_tbPLayout.setHorizontalGroup(
            nhanVien_showList_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showList_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nhanVien_showList_tbPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                .addContainerGap())
        );
        nhanVien_showList_tbPLayout.setVerticalGroup(
            nhanVien_showList_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_showList_tbPLayout.createSequentialGroup()
                .addComponent(showList_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Nhân Viên", nhanVien_showList_tbP);

        javax.swing.GroupLayout nhanVien_showData_tbPLayout = new javax.swing.GroupLayout(nhanVien_showData_tbP);
        nhanVien_showData_tbP.setLayout(nhanVien_showData_tbPLayout);
        nhanVien_showData_tbPLayout.setHorizontalGroup(
            nhanVien_showData_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        nhanVien_showData_tbPLayout.setVerticalGroup(
            nhanVien_showData_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Thống kê", nhanVien_showData_tbP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhanVien_txt_searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVien_txt_searchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVien_txt_searchIDActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        nhanVien_Form_Add add = new nhanVien_Form_Add(this);
        add.setVisible(true);
    }//GEN-LAST:event_AddActionPerformed

    private void nhanVien_txt_searchIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nhanVien_txt_searchIDPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVien_txt_searchIDPropertyChange

    private void nhanVien_txt_searchIDCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nhanVien_txt_searchIDCaretUpdate
        // TODO add your handling code here:
        showList_nv_byID_almost(nhanVien_txt_searchID.getText());
    }//GEN-LAST:event_nhanVien_txt_searchIDCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel nhanVien_showData_tbP;
    private javax.swing.JPanel nhanVien_showList_container;
    private javax.swing.JPanel nhanVien_showList_tbP;
    private javax.swing.JTextField nhanVien_txt_searchID;
    private javax.swing.JPanel showList_nav;
    // End of variables declaration//GEN-END:variables
}
