/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhanVien.View;

import Model.nhanVien;
import nhanVien.data.nhanVien_data_DAO;
import com.pro1041.util.DateHelper;
import nhanVien.data.checkNhanVien;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author hnhut
 */
public class nhanVien_Form_Edit extends javax.swing.JFrame {

    /**
     * Creates new form nhanVien_Form_Edit
     */
    private nhanVien nvM;
    private NhanVienCard nhanVienCard;
    nhanVien_data_DAO dao = new nhanVien_data_DAO();
    private String maNV_old;
    static boolean ck = true;

    public nhanVien_Form_Edit(nhanVien nvM, NhanVienCard nhanVienCard) {
        initComponents();
        this.nhanVienCard = nhanVienCard;
        this.nvM = nvM;
        maNV_old = this.nvM.getMaNhanVien();
        setForm();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void checkField(Component c) {

    }

    public void setForm() {
        Icon image;
        if (nvM.getHinhAnh() != null) {
            image = new ImageIcon(nvM.getHinhAnh());
        } else {
            image = new ImageIcon("src\\image\\user.png");
        }
        edit_btn_Image.setIcon(image);

        edit_txt_maNhanVien.setText(nvM.getMaNhanVien());
        edit_txt_hovaTen.setText(nvM.getHoVaTen());
        edit_cbb_chucVu.setSelectedItem(nvM.getChucVu() == true ? "Quản lý" : "Nhân Viên");
        if (nvM.getGioiTinh()) {
            edit_rdo_Male.setSelected(true);
        } else {
            edit_rdo_feMale.setSelected(true);
        }

        edit_date_Date.setDate(nvM.getNgaySinh());
    }

    public nhanVien getForm() {
        String maNhanVien = edit_txt_maNhanVien.getText();
        String hoVaTen = edit_txt_hovaTen.getText();
        boolean chucVu = edit_cbb_chucVu.getSelectedItem().toString().equals("Quản lý") ? true : false;
        boolean gioiTinh = edit_rdo_Male.isSelected() ? true : false;
        java.sql.Date date = new java.sql.Date(edit_date_Date.getDate().getTime());

        return new nhanVien(maNhanVien, hoVaTen, nvM.getMatKhau(), chucVu, gioiTinh, date, nvM.getEmail(), nvM.getCanCuocCongDan(), nvM.getSoDienThoai(), nvM.getHinhAnh()
        );
    }

    public void checkForm() {
        ck = true;

        if (new nhanVien_data_DAO().getCount_maNv(edit_txt_maNhanVien.getText()) == 0) {
        } else {
            JOptionPane.showMessageDialog(this, "ID đã tồn tại", "ID Error", JOptionPane.ERROR_MESSAGE);
            ck = false;
        }

        if (edit_txt_hovaTen.getText().isEmpty()) {
            edit_txt_hovaTen.setBorder(new LineBorder(Color.yellow));
            ck = false;
        } else {
            if (!checkNhanVien.kiemTraHoTen(edit_txt_hovaTen.getText())) {
                ck = false;
                edit_txt_hovaTen.setBorder(new LineBorder(Color.red));
                edit_txt_hovaTen.setText("Error! Định dạng họ và tên không đúng");
            }
        }
        Date c = edit_date_Date.getDate();
        if (DateHelper.calculateAge(c.getYear(), c.getMonth(), c.getDate()) < 15) {
            edit_erorMs.setText("Số tuổi phải lớn hơn 15");
            ck = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gioiTinh_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edit_txt_maNhanVien = new javax.swing.JTextField();
        edit_txt_name = new javax.swing.JLabel();
        edit_txt_hovaTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edit_cbb_chucVu = new javax.swing.JComboBox<>();
        edit_rdo_Male = new javax.swing.JRadioButton();
        edit_rdo_feMale = new javax.swing.JRadioButton();
        edit_btn_update = new javax.swing.JButton();
        edit_btn_Image = new javax.swing.JButton();
        edit_erorMs = new javax.swing.JLabel();
        edit_date_Date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thay đổi thông tin");

        jLabel4.setText("Mã nhân viên");

        edit_txt_maNhanVien.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        edit_txt_maNhanVien.setMargin(new java.awt.Insets(5, 9, 5, 9));

        edit_txt_name.setText("Họ và tên");

        edit_txt_hovaTen.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        edit_txt_hovaTen.setMargin(new java.awt.Insets(5, 9, 5, 9));
        edit_txt_hovaTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_txt_hovaTenMouseClicked(evt);
            }
        });
        edit_txt_hovaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_txt_hovaTenActionPerformed(evt);
            }
        });

        jLabel5.setText("Chức vụ");

        jLabel6.setText("Giới tính");

        jLabel7.setText("Ngày sinh");

        edit_cbb_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân Viên" }));

        gioiTinh_group.add(edit_rdo_Male);
        edit_rdo_Male.setText("Nam");

        gioiTinh_group.add(edit_rdo_feMale);
        edit_rdo_feMale.setText("Nữ");

        edit_btn_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit_btn_update.setText("Cập nhật");
        edit_btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btn_updateActionPerformed(evt);
            }
        });

        edit_btn_Image.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        edit_btn_Image.setText("Ảnh đại diện");
        edit_btn_Image.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit_btn_Image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edit_btn_Image.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        edit_btn_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btn_ImageActionPerformed(evt);
            }
        });

        edit_erorMs.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edit_btn_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edit_btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(edit_txt_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit_txt_maNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(edit_txt_hovaTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edit_cbb_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit_rdo_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit_rdo_feMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit_date_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edit_erorMs)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_btn_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edit_txt_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_txt_name)
                    .addComponent(edit_txt_hovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edit_cbb_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edit_rdo_Male)
                    .addComponent(edit_rdo_feMale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(edit_erorMs))
                    .addComponent(edit_date_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(edit_btn_update)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btn_updateActionPerformed
        // TODO add your handling code here:
        checkForm();
        if (ck) {
            dao.update(getForm(), maNV_old);
            nhanVienCard.updateCard(getForm());
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            this.dispose();
        }
    }//GEN-LAST:event_edit_btn_updateActionPerformed

    private void edit_btn_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btn_ImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("/src/image");
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            nvM.setHinhAnh(selectedFile.getAbsolutePath());
            edit_btn_Image.setIcon(new ImageIcon(nvM.getHinhAnh()));
            setForm();
            System.out.println("Bạn đã chọn file: " + selectedFile.getAbsolutePath());
        } else {
            System.out.println("Không có file nào được chọn");
        }
    }//GEN-LAST:event_edit_btn_ImageActionPerformed

    private void edit_txt_hovaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_txt_hovaTenActionPerformed
        // TODO add your handling code here:
        edit_txt_hovaTen.setText("");
        edit_txt_hovaTen.setBorder(new LineBorder(Color.WHITE));
    }//GEN-LAST:event_edit_txt_hovaTenActionPerformed

    private void edit_txt_hovaTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_txt_hovaTenMouseClicked
        // TODO add your handling code here:
        edit_txt_hovaTen.setText("");
        edit_txt_hovaTen.setBorder(new LineBorder(Color.WHITE));
    }//GEN-LAST:event_edit_txt_hovaTenMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit_btn_Image;
    private javax.swing.JButton edit_btn_update;
    private javax.swing.JComboBox<String> edit_cbb_chucVu;
    private com.toedter.calendar.JDateChooser edit_date_Date;
    private javax.swing.JLabel edit_erorMs;
    private javax.swing.JRadioButton edit_rdo_Male;
    private javax.swing.JRadioButton edit_rdo_feMale;
    private javax.swing.JTextField edit_txt_hovaTen;
    private javax.swing.JTextField edit_txt_maNhanVien;
    private javax.swing.JLabel edit_txt_name;
    private javax.swing.ButtonGroup gioiTinh_group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
