package View.DangNhap;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.pro1041.util.DateHelper;
import com.pro1041.util.DialogHelper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author HOANG
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }
    String Driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=quanLyCuaHangThoiTrang;encrypt=false";
    String user = "sa";
    String password = "hung";
    Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdbQuanLi = new javax.swing.JRadioButton();
        rdbNhanVien = new javax.swing.JRadioButton();
        txtmatKhau = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        btnDangKy = new javax.swing.JButton();
        txtmaNhanVien = new javax.swing.JTextField();
        txthoTen = new javax.swing.JTextField();
        txtCanCuoc = new javax.swing.JTextField();
        txtSodt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(rdbQuanLi);
        rdbQuanLi.setFont(new java.awt.Font("Lexend Deca", 0, 24)); // NOI18N
        rdbQuanLi.setSelected(true);
        rdbQuanLi.setText("Quản lý");
        jPanel1.add(rdbQuanLi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, 40));

        buttonGroup2.add(rdbNhanVien);
        rdbNhanVien.setFont(new java.awt.Font("Lexend Deca", 0, 24)); // NOI18N
        rdbNhanVien.setText("Nhân viên");
        jPanel1.add(rdbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, 40));

        txtmatKhau.setFont(new java.awt.Font("Lexend Deca", 0, 20));
        PromptSupport.setPrompt("Mật khẩu", txtmatKhau);
        txtmatKhau.setBorder(null);
        txtmatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(txtmatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 330, 40));

        buttonGroup1.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Lexend Deca", 0, 24)); // NOI18N
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");
        jPanel1.add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, 40));

        buttonGroup1.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Lexend Deca", 0, 24)); // NOI18N
        rdbNu.setText("Nữ");
        jPanel1.add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, -1, 40));

        btnDangKy.setFont(new java.awt.Font("Lexend Deca", 0, 22)); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, 210, 60));

        txtmaNhanVien.setFont(new java.awt.Font("Lexend Deca", 0, 20));
        PromptSupport.setPrompt("Mã nhân viên", txtmaNhanVien);
        txtmaNhanVien.setBorder(null);
        txtmaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(txtmaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 330, 40));

        txthoTen.setFont(new java.awt.Font("Lexend Deca", 0, 20)); // NOI18N
        PromptSupport.setPrompt("Tên nhân viên", txthoTen);
        txthoTen.setBorder(null);
        txthoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoTenActionPerformed(evt);
            }
        });
        jPanel1.add(txthoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 330, 40));

        txtCanCuoc.setFont(new java.awt.Font("Lexend Deca", 0, 20));
        PromptSupport.setPrompt("Căn cước công dân", txtCanCuoc);
        txtCanCuoc.setBorder(null);
        txtCanCuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanCuocActionPerformed(evt);
            }
        });
        jPanel1.add(txtCanCuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 330, 40));

        txtSodt.setFont(new java.awt.Font("Lexend Deca", 0, 20));
        PromptSupport.setPrompt("Số điện thoại", txtSodt);
        txtSodt.setBorder(null);
        txtSodt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSodtActionPerformed(evt);
            }
        });
        jPanel1.add(txtSodt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 330, 40));

        jLabel2.setFont(new java.awt.Font("Lexend Deca", 0, 18)); // NOI18N
        jLabel2.setText(" Đã có tài khoản? Đăng nhập tại");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 730, 290, -1));

        jLabel3.setFont(new java.awt.Font("Lexend Deca", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("đây");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 730, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lexend Deca", 1, 48)); // NOI18N
        jLabel4.setText("Đăng ký");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, -1));
        jPanel1.add(DateChooserNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 330, 40));

        text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dang-ki.png"))); // NOI18N
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatKhauActionPerformed

    private void txtmaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaNhanVienActionPerformed

    private void txthoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoTenActionPerformed

    private void txtCanCuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanCuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanCuocActionPerformed

    private void txtSodtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSodtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        int dk = JOptionPane.showConfirmDialog(this, "Bạn Muốn Đăng Kí?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (dk != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            if (txtmaNhanVien.getText().equals("") || txtmatKhau.getText().equals("") || txthoTen.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không Được Để Trống");
                return; // Kết thúc phương thức nếu có trường rỗng
            }
            Class.forName(Driver);
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "INSERT INTO nhanVien (maNhanVien, hoVaten, chucVu, ngaySinh, gioiTinh, canCuocCongDan, soDienThoai, hinhAnh, matKhau) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtmaNhanVien.getText());
            ps.setString(2, txthoTen.getText());
            if (rdbQuanLi.isSelected()) {
                ps.setBoolean(3, true);
            } else if (rdbNhanVien.isSelected()) {
                ps.setBoolean(3, false);
            } else {
                JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Giới Tính");
            }
            String dateStr = DateHelper.toString(DateChooserNgaySinh.getDate(), "yyyy-MM-dd");
            System.out.println(dateStr);
            java.sql.Date dateOfBirth = new java.sql.Date(DateHelper.toDate(dateStr, "yyyy-MM-dd").getTime()); // Chuyển đổi thành java.sql.Date

            ps.setDate(4, dateOfBirth);
            if (rdbNam.isSelected()) {
                ps.setBoolean(5, true); // Nam
            } else if (rdbNu.isSelected()) {
                ps.setBoolean(5, false); // Nữ
            } else {
                JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Giới Tính");
            }

            ps.setString(6, txtCanCuoc.getText());
            ps.setString(7, txtSodt.getText());
            ps.setString(8, null);
            ps.setString(9, txtmatKhau.getText());

            int n = ps.executeUpdate();
            if (n != 0) {
                JOptionPane.showMessageDialog(this, "Đăng Kí Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Đăng Kí Thất Bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DialogHelper.alert("Đăng ký thành công");
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        FlatMacLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserNgaySinh;
    private javax.swing.JButton btnDangKy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNhanVien;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JRadioButton rdbQuanLi;
    private javax.swing.JLabel text;
    private javax.swing.JTextField txtCanCuoc;
    private javax.swing.JTextField txtSodt;
    private javax.swing.JTextField txthoTen;
    private javax.swing.JTextField txtmaNhanVien;
    private javax.swing.JTextField txtmatKhau;
    // End of variables declaration//GEN-END:variables
}
