package View.SanPham;

import Model.sanPham;
import View.Main;
import com.pro1041.dao.DAO_sanPham;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import View.SanPham.them;
import com.pro1041.util.DialogHelper;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author HOANG
 */
public class card extends javax.swing.JPanel {

    String setDis = null;
    DAO_sanPham dao = new DAO_sanPham();
    String idSanPham;
    sanPham sp;
    DecimalFormat df = new DecimalFormat("#,###.### đồng");

    /**
     * Creates new form card
     */
    public card(sanPham sp) {
        initComponents();
        if (sp.getHinhAnh() != null) {
            setIcon(new ImageIcon(this.getClass().getResource("/image/" + sp.getHinhAnh())), lblHinh);
        }
        lblTen.setText("Tên sản phẩm: " + sp.getTenSanPham());
        lblGia.setText("Giá: " + String.valueOf(df.format(sp.getDonGia())));
        this.idSanPham = sp.getMaSanPham();
        this.sp = sp;
        hoverOut();
    }

    public void setIcon(ImageIcon ic, JLabel jl) {
        jl.setIcon(new ImageIcon(ic.getImage().getScaledInstance(jl.getPreferredSize().width, jl.getPreferredSize().height, 0)));
    }

    public void hoverIn() {
        jPanel2.setVisible(true);
        jPanel1.repaint();
        validate();
    }

    public void hoverOut() {
        jPanel2.setVisible(false);
        jPanel1.repaint();
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnXem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lblTenSP = new javax.swing.JLabel();
        lblGiaSP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(267, 350));

        jPanel1.setBackground(new java.awt.Color(228, 225, 214));
        jPanel1.setPreferredSize(new java.awt.Dimension(257, 310));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinh.setBackground(new java.awt.Color(228, 225, 214));
        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHinh.setOpaque(true);
        lblHinh.setPreferredSize(new java.awt.Dimension(228, 194));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHinhMouseExited(evt);
            }
        });
        jPanel1.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 250, -1));

        lblTen.setFont(new java.awt.Font("Lexend Deca", 0, 16)); // NOI18N
        lblTen.setText("Tên sản phẩm:");
        jPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblGia.setFont(new java.awt.Font("Lexend Deca", 0, 16)); // NOI18N
        lblGia.setText("Giá:");
        jPanel1.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(228, 225, 214));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        btnXem.setBackground(new java.awt.Color(145, 169, 120));
        btnXem.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N
        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(211, 37, 71));
        btnXoa.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 209, 84));
        btnSua.setFont(new java.awt.Font("Lexend Deca", 0, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnXem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 240, 50));
        jPanel1.add(lblTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 206, 118, -1));
        jPanel1.add(lblGiaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 212, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        hoverIn();
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        hoverOut();
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        hoverIn();
    }//GEN-LAST:event_jPanel2MouseEntered

    private void lblHinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseEntered
        // TODO add your handling code here:
        hoverIn();
    }//GEN-LAST:event_lblHinhMouseEntered

    private void lblHinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseExited
        // TODO add your handling code here:
        hoverOut();
        if (!jPanel2.isVisible()) {
            hoverOut();
            System.out.println("a");
        }
    }//GEN-LAST:event_lblHinhMouseExited

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        setDis = "1";
        them them = new them(setDis);
        them.setVisible(true);
        them.setLocationRelativeTo(null);
        them.setForm(sp);
    }//GEN-LAST:event_btnXemActionPerformed

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        hoverIn();
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        hoverIn();
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int confirmResult = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

        if (confirmResult == JOptionPane.YES_OPTION) {
            dao.delete(idSanPham);
            DialogHelper.alert("Xóa thành công");
            Main.sanPham.loadToData();
        } else {
            System.out.println(evt);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        hoverIn();
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        hoverOut();
        if (!jPanel2.isVisible()) {
            hoverOut();
        }
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        setDis = null;
        them them = new them(setDis);
        them.setVisible(true);
        them.setLocationRelativeTo(null);
        them.setForm(sp);
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaSP;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenSP;
    // End of variables declaration//GEN-END:variables
}
